language: node_js
node_js:
  - '8'
install:
  - npm install
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm run lint
env:
  - MOZ_HEADLESS=1
addons:
  firefox: "latest"
