# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://drive_abci:26658"

# A custom human readable name for this node
#moniker = ""

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: goleveldb | cleveldb | boltdb
# * goleveldb (github.com/syndtr/goleveldb - most popular implementation)
#   - pure go
#   - stable
# * cleveldb (uses levigo wrapper)
#   - fast
#   - requires gcc
#   - use cleveldb build tag (go build -tags cleveldb)
# * boltdb (uses etcd's fork of bolt - github.com/etcd-io/bbolt)
#   - EXPERIMENTAL
#   - may be faster is some use-cases (random reads - indexer)
#   - use boltdb build tag (go build -tags boltdb)
db_backend = "goleveldb"

# Database directory
db_dir = "/data/db"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"
#log_level = "*:debug"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "/data/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "/data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "/data/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# Maximum size of request body, in bytes
max_body_bytes = 1000000

# Maximum size of request header, in bytes
max_header_bytes = 1048576

# The path to a file containing certificate that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_cert_file = ""

# The path to a file containing matching private key that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
#external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "b5f25240149ff85f3fa77ad29e23973614bfae11@34.215.98.56:26656,fa1743659cb0439488a74b637ab1c9158176c6c4@34.212.137.130:26656,fe8ac577b1f2f796b127e74e42ed21b1d96d3154@54.189.154.241:26656,5945635806145a2fa6a3c1e9e843d67ddc6379e6@54.187.95.200:26656,2e6a2f40eed1e7b608be3e71174c7d148d7c871f@34.212.69.250:26656,d6d453dc09c457a03924d58d96a88f35429b9552@34.214.143.249:26656,1eac21111f1bd401cdfe2966552b2259f0d1cb14@34.215.175.142:26656,53c72202d4f703ca770940c58fccc14c467bcb32@54.214.117.53:26656,014503e8f308693299871b2d955b14f27ccf0ea7@35.166.207.191:26656,3d22c41970fb81b543d1a5c8d9896558ac17f677@52.13.161.110:26656,05046c05694045e1d539773be0d017525ce94e43@52.39.238.5:26656,f69f9f0874c0de517f060baf689de3375b3bf3ff@54.188.94.141:26656,d2186d0f3adb80978c67540a08669ba39c3d987f@52.36.80.182:26656,f0bce1f8a5d795892c981b5f82a3c1e6363e76ad@54.245.142.243:26656,6c60a6ee55550feeb49b1654dba1a89102bc1865@52.24.198.145:26656,0240aa772e9de47ff27f7f2a4d00c43a540cb81e@52.33.207.244:26656,72a8d61aef389ea012a2e0203d8ec15f44bd8a4c@54.149.72.137:26656,2c3f466072c2f49587ec85831e36025b11236256@52.43.158.21:26656,54ad1001c3f27fdb7f98aa8027ab7a3c0ef4f135@54.187.215.38:26656,26065546a10e25f0409fb4b94ea054420b469c05@34.220.134.51:26656,8833cd58d1364eb228673be1ed5e67b38bc8ecf4@52.24.203.28:26656,17675b12fc2c8e60020a299fc2592a3a91a1b3c9@54.212.114.204:26656,1d6dda8d5cf1650a92efe4d8efa66047d0e2093e@54.244.36.140:26656,f78573190d6fc40febc3d36dde36acb77ee886e1@34.222.130.18:26656,d9fcd5e7717de7559a92da1b666720a36811937d@52.34.219.71:26656,d85c1c7ce5e2caeab331e318b71530c7a9e07f41@34.211.141.125:26656,52eb315885556a49daebe5dcef68be2a63c1a246@35.162.23.56:26656,637e55b0c9cce4f8bf97c4a4f1b92cb29c5dd3d8@52.24.232.168:26656,ebee41eddd8eb8f2ae06a9fd6f5eee6e4130818d@18.237.190.60:26656,530e5c5621ecc9a8f51ba4c9f0f0faf325cac797@54.245.4.139:26656,cee65a3db83f1a58fa9a6c9a5bcd94825542d8cf@18.236.254.166:26656,9fbd5829f60a8a5b7dbbbef95363b2499aebfe89@52.13.92.167:26656,326e1508dc92225091e6c10c1f23acd8bcbddd70@34.222.49.202:26656,4b9fab30bb14b81293f0f2de7c010e66a119b8cf@35.166.50.163:26656,e64986d0f952446f7b2e2b985d308c6200b5b9ae@34.223.227.233:26656,1d2a195b604cc1d49de69c2f5e2668dcb3dbc07f@35.166.226.20:26656,ee56fcd24c397b43660403f41dde3695897dfb2a@54.149.99.4:26656,fdfd857aa0e32b75a0d8166183d2a29a710dd36f@34.222.164.12:26656,27ee6f484043b0cf5e637d8f77ebd2866ace8c22@54.185.222.73:26656,f7f0a4c211c7b7df69fd2fa2feb2620307bf9748@34.215.228.175:26656,ed47ab26c12589a76110af9c2929daaf9514f7f9@54.187.178.138:26656,ffd643b37bb3b01f06f6a10d9670a2bd934af2f3@18.237.88.106:26656,d9e1156a3ff95ff2cfd2ebd98cba62ec7111485e@54.200.212.117:26656,2412669d5c08a59f275ec37b58a9385b22d6d6be@34.212.245.91:26656,ce683e4ba5215ebd14c4deea4e2667efd9ae6295@54.184.225.122:26656,09b5778ab0bdd98a5b15b70576f6831843c5b689@34.221.111.92:26656,3547d551e01ef0c415fc5f07b0b37a3999783944@54.71.60.103:26656,ea893f32ca16729d4a958e092f3c4809cb1acbee@34.221.141.147:26656,f25dadce2572a401ead45b4b70df60dae2c30d26@54.200.82.127:26656"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "/data/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

# Maximum size of a single transaction.
# NOTE: the max size of a tx transmitted over the network is {max_tx_bytes} + {amino overhead}.
max_tx_bytes = 1048576

##### fast sync configuration options #####
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
version = "v0"

##### consensus configuration options #####
[consensus]

wal_file = "/data/db/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = false
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "drive_tendermint"
