# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://drive_abci:26658"

# A custom human readable name for this node
#moniker = ""

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: goleveldb | cleveldb | boltdb
# * goleveldb (github.com/syndtr/goleveldb - most popular implementation)
#   - pure go
#   - stable
# * cleveldb (uses levigo wrapper)
#   - fast
#   - requires gcc
#   - use cleveldb build tag (go build -tags cleveldb)
# * boltdb (uses etcd's fork of bolt - github.com/etcd-io/bbolt)
#   - EXPERIMENTAL
#   - may be faster is some use-cases (random reads - indexer)
#   - use boltdb build tag (go build -tags boltdb)
db_backend = "goleveldb"

# Database directory
db_dir = "/data/db"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"
#log_level = "*:debug"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "/data/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "/data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "/data/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# Maximum size of request body, in bytes
max_body_bytes = 1000000

# Maximum size of request header, in bytes
max_header_bytes = 1048576

# The path to a file containing certificate that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_cert_file = ""

# The path to a file containing matching private key that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
#external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "cfb18c49c81c42e2873f9df002af48d12166c114@52.89.124.211:26656,a7b10f2f4aa47f2ae31178d8af67f1700867543f@34.209.193.190:26656,807f1b935808e8df64dad8fa03a4ede2061bbdaf@35.166.6.110:26656,a7abc41a14a611533768f4ccc158984e38a28605@34.221.28.0:26656,062779911a3c5269efeee02c3591da3bb3e9bc83@54.203.118.246:26656,ded216eada1b9036b9500d2e9d48d7991df6b4d7@35.162.228.3:26656,337787b15e258031fb4b6f88ccc4e2649b963a67@54.202.168.30:26656,fa6aa5e23e99950091df102f47e029d10a32cdb5@52.33.172.246:26656,40264599f5051cc6e3f8dfa3ef8759244e0efc6d@52.10.63.195:26656,ef10d6dbb84780c53ab848d09383ce7de3fc82c1@34.220.63.84:26656,297aa53a1521f9c6a69e623d3fba02d32cb94a61@35.167.48.167:26656,94884464d683e605cd23eac70c8a03bf744a1d2a@54.212.9.170:26656,9a702bba2353947f5a833bbe950fc47b89226cc6@34.220.78.165:26656,c7c37affa50c6f4af531c52ebbd0bdd79b14b8f2@54.187.122.146:26656,89f6d0123b1f4088a292df88f8ce1eadb34a3fc5@50.112.197.142:26656,f303a3136f1386f1443758c4617d815aae5685c6@34.219.251.242:26656,fa5c63ecc3b5bba8acd010d441f309281233a6bd@34.216.14.190:26656,1e276c70c81a585e0142ec32ef57fd49946ca098@34.222.50.204:26656,93ea5b445a3f110341323ecc042fadea1cba4883@34.221.137.203:26656,3664aa11dedbb6e744f630e2d9a1981fb00ba632@52.24.144.3:26656,4098c9670e434b4806cde33c9e99f44205176d55@18.236.165.125:26656,94ad03c3830ef59a8def6a880e70ea360d22029b@54.188.167.159:26656,d7fbac85690a3a9745a7d541be5c986b2763e627@54.201.41.131:26656,fc8218f07de901cb601636107ab47843289c3f94@34.219.137.212:26656,e230b7ca806197db3aa6df602596759b5bcfde4a@34.220.50.187:26656,367071b16601bc37b5b385b9ec25623fbef93f1a@54.202.66.234:26656,125cbe9ea28793e3e2f7ac5553bbde77c0dce707@34.209.42.117:26656,20253b9295212a386124cf247eb2d595bea24077@34.217.19.154:26656,d86734a9b0ffcaa40c4c0977b276b1758386d8db@34.214.193.163:26656,581a6237a95c31e2ccab95354063a8d121b884c3@54.191.242.14:26656,9ad5e9ded0e9aa5936d1a1423ae27f9cbf089778@18.236.198.228:26656,68ecddc0e67777f60729ee7ffc544a3c9cf23293@34.212.176.135:26656,1b646b8411306004be807f8032f3bab3935120ac@52.13.98.99:26656,e440a10f5e02dd0080881287973a28d2b05909ea@52.26.203.151:26656,063683497e96e45759831008a8c70f00049fe454@52.12.32.108:26656,350cd8f5297c590eb5299d320cce97c0a16aed43@52.43.56.134:26656,21dd8973c4187964b4a2f95316b18d36d6271ce6@52.36.222.114:26656,4bd11463f7c1d9f9685dcb1351ca20678ca1fc0f@34.221.146.34:26656,a32e712f874bb777dc6c313760c6bd93465e41b2@34.219.128.5:26656,cf34b5bde2c39260cdf3adf06b1a978cac27ba37@54.213.244.91:26656,dc732296ea139bd45204ca9984f379be452e4934@34.221.55.32:26656,8fcbe779aa2a80e9b903542e347b226a5fd7243d@18.237.78.167:26656,fdbff4cb41342950cd37693bdda9afd165368099@54.214.164.230:26656,20324359bb7fd03850e25c7599fc3eb7e2066a08@35.167.1.167:26656,461e7ddcbe0f220e5cd9da6c0fe0d4021e2d9c86@54.245.150.218:26656,3e001409c4703ff94cb3ade1cf8274bb8b93b3b0@34.222.243.95:26656,8f05fd0752a4c0c64768a5edd56342a0ba2fcb76@54.190.26.164:26656,92f43926414385fbdcc151e76ec9a4a23212e11c@34.222.46.203:26656,d6c662a09a94b7cd54c5acadaced6e921b39fb61@34.218.66.230:26656"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "/data/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

# Maximum size of a single transaction.
# NOTE: the max size of a tx transmitted over the network is {max_tx_bytes} + {amino overhead}.
max_tx_bytes = 1048576

##### fast sync configuration options #####
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
version = "v0"

##### consensus configuration options #####
[consensus]

wal_file = "/data/db/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = false
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "drive_tendermint"
