# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://drive_abci:26658"

# A custom human readable name for this node
#moniker = ""

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: goleveldb | cleveldb | boltdb
# * goleveldb (github.com/syndtr/goleveldb - most popular implementation)
#   - pure go
#   - stable
# * cleveldb (uses levigo wrapper)
#   - fast
#   - requires gcc
#   - use cleveldb build tag (go build -tags cleveldb)
# * boltdb (uses etcd's fork of bolt - github.com/etcd-io/bbolt)
#   - EXPERIMENTAL
#   - may be faster is some use-cases (random reads - indexer)
#   - use boltdb build tag (go build -tags boltdb)
db_backend = "goleveldb"

# Database directory
db_dir = "/data/db"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"
#log_level = "*:debug"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "/data/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "/data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "/data/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# Maximum size of request body, in bytes
max_body_bytes = 1000000

# Maximum size of request header, in bytes
max_header_bytes = 1048576

# The path to a file containing certificate that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_cert_file = ""

# The path to a file containing matching private key that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
#external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "64024cac4c66e79f5e26bf7bc25549695a93d22c@34.219.70.50:26656,209683e1c4ae74a5081d1becbfc20e76f44cb7b3@52.89.124.211:26656,efd06669261cb33e510537df5f6cc3d981f08c17@34.209.193.190:26656,cae820ae1a644d2f4719b910607a6d7f752018b9@35.166.6.110:26656,0d1948913a7d315774cf874331f33acb146aef92@34.221.28.0:26656,08a861bd6220703e139bcaf0924d4854202fdbcc@54.203.118.246:26656,2b419ceb03a855313335cf3f517a32be6fc26f98@35.162.228.3:26656,57ba0a976ae1367b5d5ecd42f95ff71b9fcf0150@54.202.168.30:26656,faecb5b9b45e6bed9aa16c3eae5e20061d8f290c@52.33.172.246:26656,1ecd3c7bab78bbf82a22b1230e6ee74e4687954d@52.10.63.195:26656,500b177fe1e24ca1a4b3ef06f29eed4bbec7953a@34.220.63.84:26656,2b3bb81a9ad135ba5ac59c70e3f7b1c389a68374@35.167.48.167:26656,c8aa97add92b0e6c48bee51d969f5cb22d21b443@54.212.9.170:26656,a1eba54c482e47ab185c63a444e919570b76e81d@34.220.78.165:26656,a78d5c9f7f35e57f37cd974148570f85d9c4a6dd@54.187.122.146:26656,a68b010c9b26e029dde5ce64ebf34a421e5cecde@50.112.197.142:26656,14206d8b57d50a12e11dbf5efcb12c5af890d853@34.219.251.242:26656,c53906475396c4146d1482c8a41995d548cc665c@34.216.14.190:26656,704366e8109d6cb18ddb0e71d143a5d9b4ced5e4@34.222.50.204:26656,87afb1fe5c5322179bd559bf9332e8a69369f7ea@34.221.137.203:26656,23f5da3b41d91486530b4aa37971a2ecf3e0ef53@52.24.144.3:26656,3168eaff279a836b7ae388eb5231d2076e6eac87@18.236.165.125:26656,6e8019e4d18a8d55f4874cdc27535fcca5a9dfa6@54.188.167.159:26656,7d6e0a2e8fb21fd132b99ed716fe54961136be3b@54.201.41.131:26656,023349847d3806f2acd1bdb74be3351e3bb82a08@34.219.137.212:26656,10be0f5dbe7878eac465c4712748815d447498ad@34.220.50.187:26656,d0142db1a660b877083c9c240c01fbe78d97d1a9@54.202.66.234:26656,802a02f9c086c68d291eb7e08eec591341e1eae4@34.209.42.117:26656,450db0cd5f9fafd1de71ced453a3451b6ed9ace0@34.217.19.154:26656,8f7074d02db3aa47b4a591f10dcdddd888381769@34.214.193.163:26656,769dc2c018b31ce1b7dfcf5ff1b1135d4006c868@54.191.242.14:26656,3fc344c1a6a6dd6ad212a3f8024d7873bc000a50@18.236.198.228:26656,72c8e38e25ca5fbfa866590ff03d0e2acfebd26b@34.212.176.135:26656,942a4e29d8302d64418c67ce9495f8149a46433f@52.13.98.99:26656,ac9b81c22f2462cb90f0ecb161dd88f0362e8873@52.26.203.151:26656,c0e89e937cd417f1db3a87b72bad01e729feb54f@52.12.32.108:26656,58b303cc1bd0c7a3df192d664ce131fb905b5e8a@52.43.56.134:26656,f9bf22af598b1fff0488cfa0d105fdb9a6e6fe40@52.36.222.114:26656,e58a66dec31c5f7f1e36145d297a4e33e9ecfe80@34.221.146.34:26656,83e121611796e73cc613e11068939bc6d2786754@34.219.128.5:26656,26083bed363db6dbc4a6d0745ee28c8b5da1fc32@34.221.55.32:26656,0e81934d814eea4bf2129611952cd87456993de0@18.237.78.167:26656,0af80ec001021ef2808c782a450c84aa94394796@54.214.164.230:26656,414dce3b1e9b00858810939ae99da48c098787bf@35.167.1.167:26656,fa8b38030f924dbe3734cf46104abbc619bae337@54.245.150.218:26656,229103029af94b41ca8966ed7842ca422c877354@34.222.243.95:26656,e187a565d9f23d9bed2a3afc182470007135fd7a@54.190.26.164:26656,65ccefeb917e94eab6dc250cc159c26d09819550@34.222.46.203:26656,843a48e6e8e0bfff5e71dcab0425c47054bbd2ac@34.218.66.230:26656"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "/data/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

# Maximum size of a single transaction.
# NOTE: the max size of a tx transmitted over the network is {max_tx_bytes} + {amino overhead}.
max_tx_bytes = 1048576

##### fast sync configuration options #####
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
version = "v0"

##### consensus configuration options #####
[consensus]

wal_file = "/data/db/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = false
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "drive_tendermint"
