# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://drive_abci:26658"

# A custom human readable name for this node
#moniker = ""

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: goleveldb | cleveldb | boltdb
# * goleveldb (github.com/syndtr/goleveldb - most popular implementation)
#   - pure go
#   - stable
# * cleveldb (uses levigo wrapper)
#   - fast
#   - requires gcc
#   - use cleveldb build tag (go build -tags cleveldb)
# * boltdb (uses etcd's fork of bolt - github.com/etcd-io/bbolt)
#   - EXPERIMENTAL
#   - may be faster is some use-cases (random reads - indexer)
#   - use boltdb build tag (go build -tags boltdb)
db_backend = "goleveldb"

# Database directory
db_dir = "data"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"
#log_level = "*:debug"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "data/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "data/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# Maximum size of request body, in bytes
max_body_bytes = 1000000

# Maximum size of request header, in bytes
max_header_bytes = 1048576

# The path to a file containing certificate that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_cert_file = ""

# The path to a file containing matching private key that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
#external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "08dd8e2b1968c1323b9460949971132653ece7d8@54.69.71.240:26656,622758cfb580133f2a33b1a9e7f3bf1591da299d@34.212.169.216:26656,f39664e7d911c42ce17cc0f4c8cc322f1b72c29e@34.214.12.133:26656,27904c3833d4d8d436152bb9138fb7a18fb071fe@54.190.136.191:26656,23e501d4eaf2edc1d5a49f6349327e9d4fb4ccdb@34.221.185.231:26656,520378c6ba73aebab3d1e25388d1b9a6ddc2ad86@18.236.73.143:26656,84b58e977d1e50fb345e03395d6a411adba74da9@35.167.241.7:26656,85f7bb17e40a49d6724504ca5caa6df8e42b74e4@52.33.251.111:26656,2570192e340943293eaba0d7d71182de01fe79a6@34.221.226.198:26656,7ac52a4464c5047d22a84eca3d218202277e6db0@54.202.214.68:26656,b575d09fe651357dc677b5d5c2ec0982251e7dca@54.186.22.30:26656,86008634cb79d53fb6c286a6e682c0891328ac2e@54.186.129.244:26656,4ab0e5e0c56adf0347d17f67171be54cca0a02e9@54.186.145.12:26656,c73217945855cedf1fc196b584fa5632538e0664@52.88.52.65:26656,9659193b7d35b0f4935e0ce81e0baed15c19053a@54.190.1.129:26656,3527b5004648540a489492f1e9a5aa272bc0832b@34.216.133.190:26656,9e9e0b8252bd58ea19caa31737b2d2172fb0cef9@34.221.5.65:26656,2b1817b5eca46f5852a4d4865c5bd8f007a85848@54.149.181.16:26656,1ac504d40d879437250622474b636ed1ca723945@54.203.2.102:26656,d8eb0fa388c3753c9a8444d421a79bf8e6c7143a@18.236.235.220:26656,49fc482748d0426146e21a7e453cc4c9c2438d54@18.236.139.199:26656,d748a3334109e51793ae735220e19b03fc1ed568@34.220.38.59:26656,fe6d601370186e71fc1812d3f616b223137fc9a1@54.244.159.60:26656,62a0c0d795424081d9cbb5ab1296398859b736eb@18.237.255.133:26656,cbf9dad753193e6620d678368240aa5657ab530e@34.220.159.57:26656,8200d0ca52f3296729232f1b741b24d8d7137232@18.237.194.30:26656,e0c512cd361e49c1117bc1f881223cb558bc37ab@52.32.251.203:26656,d7ff609df651cf448ad5fba7f35e2de61057ff3a@34.222.91.196:26656,a3dcfd041b12c6629c41a670377c7a945da3a848@34.219.43.9:26656,c1499a9650a96a8034e606df5b90f76b36051021@54.244.203.43:26656,a6045508e21d4946b0b6a8f9924882a6bdf0fbc9@54.245.217.116:26656,b88de2d0f943f4e0748039c0d6d72c6511032469@54.189.121.60:26656,77316bb767e52216b777f171a1382aa573ec6608@52.88.38.138:26656,c1b6760ce4267b4ea7e90d54b0e9d4ab95483051@54.185.186.111:26656,7aec8ce958561379eb85ebadec1f0c93c83db6e8@35.164.4.147:26656,881b7d135b29797fcb652c7c7807c9f2b243fe9a@54.188.72.112:26656,f52237cfc900b26589969bd93b0ca775ebe00f76@52.88.13.87:26656,84804842f805684bb831b5799d3628a5e31e6fef@54.149.99.26:26656,fc85b3e8212c17f231a332395a3923a7202ba794@54.212.206.131:26656,856d39ed1d493a5436188c14bc2e11d87863f393@52.25.73.91:26656,4ab81caa5be52118e442496e31b51d5e7fb1e020@54.187.128.127:26656,a97df28a6961287acac36b7e8632e9988e614841@34.223.226.20:26656,74866833db1577a9916a09592f5ab76b455db15d@35.167.226.182:26656,de7241a53bb157cb78429e79b3074f87801721d8@54.189.73.226:26656,7220ea2cc1474dbb979171932b191643dc508519@34.219.79.193:26656,49b3cd3c6fd8eccd3e81b468512b91a87e22a60a@54.186.133.94:26656,0786707a967d5032ce552d3652de9d724acf820c@54.190.26.250:26656,bb943d27e94ddeb18cef0bb8772df4b09a727e7d@54.184.71.154:26656,d45a481e4845fcca3f14f333803190eff05f5b0d@54.200.73.105:26656"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "data/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

# Maximum size of a single transaction.
# NOTE: the max size of a tx transmitted over the network is {max_tx_bytes} + {amino overhead}.
max_tx_bytes = 1048576

##### fast sync configuration options #####
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
version = "v0"

##### consensus configuration options #####
[consensus]

wal_file = "data/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "3m"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "drive_tendermint"
