# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: Any path below can be absolute (e.g. "/var/myawesomeapp/data") or
# relative to the home directory (e.g. "data"). The home directory is
# "$HOME/.tendermint" by default, but could be changed via $TMHOME env variable
# or --home cmd flag.

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://drive_abci:26658"

# A custom human readable name for this node
#moniker = ""

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: goleveldb | cleveldb | boltdb
# * goleveldb (github.com/syndtr/goleveldb - most popular implementation)
#   - pure go
#   - stable
# * cleveldb (uses levigo wrapper)
#   - fast
#   - requires gcc
#   - use cleveldb build tag (go build -tags cleveldb)
# * boltdb (uses etcd's fork of bolt - github.com/etcd-io/bbolt)
#   - EXPERIMENTAL
#   - may be faster is some use-cases (random reads - indexer)
#   - use boltdb build tag (go build -tags boltdb)
db_backend = "goleveldb"

# Database directory
db_dir = "data"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"
#log_level = "*:debug"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "data/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "data/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# Maximum size of request body, in bytes
max_body_bytes = 1000000

# Maximum size of request header, in bytes
max_header_bytes = 1048576

# The path to a file containing certificate that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_cert_file = ""

# The path to a file containing matching private key that is used to create the HTTPS server.
# Migth be either absolute path or path related to tendermint's config directory.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server.
# Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
#external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "fdabddda2940d6ae8efb18d846e60489dada29d5@54.69.71.240:26656,2e61ca71214bf96576ec1f342ff08eaed39b33e5@34.212.169.216:26656,5c3e7355ef653323189d3e2c063adf3f39d5514a@34.214.12.133:26656,e4dae56ca1f29de8ad3a58521bdf1e5439b0f17e@54.190.136.191:26656,266382d0850f0214d6e8ad2354cb7693c33939e8@34.221.185.231:26656,dd53e1da391f8602d778a5e6edb1416001aa4ac9@18.236.73.143:26656,3604e7f62c292454617ca377b818aef3dee08bea@35.167.241.7:26656,ae707efafdaccb0bc50e4e64bf708f25762729e8@52.33.251.111:26656,b338130c6ac4f55478ea0e0ab28972d5f14de392@34.221.226.198:26656,67adce3922218296b2f299930a7ba607c64afa8e@54.202.214.68:26656,3b6fce5de097d6399e0b08cdf0bc48aa9d1038c7@54.186.22.30:26656,f082638a46117c8c292141560076f6bb9e24df25@54.186.129.244:26656,3b9dc53cb5c4bc9259233ee76c585a67273e46dc@54.186.145.12:26656,7d79a247e295f76dc7cabcfaa42d64c1cbc74b95@52.88.52.65:26656,3bc9a49553c39035e236eaed4f6cdcfd837c2b4e@54.190.1.129:26656,18e1d19666c3ab192a5e18b6c0298c75e22086f9@34.216.133.190:26656,01c3033055d2fddf138659123a9fd8ad1e682a34@34.221.5.65:26656,42ef1f9803f03a61c23ddde00f38489a0671ca03@54.149.181.16:26656,a0a3b94fd3634b3c607a05c72420defbd3a51563@54.203.2.102:26656,ebf45a6fc15bb09aa083fd3cfa6b24826ac0b0e6@18.236.235.220:26656,4b979a87b2e8238d45bb7327bef3372692bc1975@18.236.139.199:26656,57229b0b1b823ab3222a7b7e5b1222146e19eb27@34.220.38.59:26656,8296b4f63bb206b51c3f7e8ff8569e8de891f548@54.244.159.60:26656,5753e074cbec7e1aaae14c4129d3ed97333d8e2a@18.237.255.133:26656,bbf1f47a82402cd5f4e4b59efc4a882bd9db4903@34.220.159.57:26656,dfdfcd05a3819cd63627e384c0b21935e502e609@18.237.194.30:26656,8232569141191227556e4061143a847ef10bb0c3@52.32.251.203:26656,0545b497087dc9127596f414a6f41a991ac1150f@34.222.91.196:26656,0b12f68d0a0bf65b4ab91320c396d71b2ff2a8a7@34.219.43.9:26656,f03c2ef5263972149577aa639736f3404575e921@54.244.203.43:26656,1834ca365a4658b4dbae228fddbed71cf89956e1@54.245.217.116:26656,e149fdb911d196ea6d7c812aad34d0457183b24f@54.189.121.60:26656,a9f3cff606ad7394828bc669c996fd6fb426f67f@52.88.38.138:26656,c4435086e12aa5de902a4b051dfd0cce5ff92b2b@54.185.186.111:26656,7acfc953971cb4cee4814d92901f94804f2da56f@35.164.4.147:26656,f1e030118b671a82566ea37da7b15f5b8212591e@54.188.72.112:26656,98aac72a62603272e08d3d32e57a390a58bf0a38@52.88.13.87:26656,32ddec809f21916fa4d8bcd8a3e56b7bb326c81c@54.149.99.26:26656,8d95fdb486779ed5e92b7aaa3bab1e419c5bef05@54.212.206.131:26656,33dbfaf005e8f90f5d6905427ef32b4aade396e1@52.25.73.91:26656,7e6d64e492f669ea5fa46a397228d13186e6f759@54.187.128.127:26656,5e761a3f5326c405c4bc85488d472607a03e0c48@34.223.226.20:26656,8c6104d745240bd9468fe0fb4e03d9c921159dfa@35.167.226.182:26656,f4dabb32016a010ed80a19320be45ecd6b8c4ea6@54.189.73.226:26656,710d18542a24ce8698db760b32be5a079863dfbc@34.219.79.193:26656,789f01b4064e50a34e77f7696c366488ec1824af@54.186.133.94:26656,eb80b6d6294876218a1e1a4528f535b5d37e3ae5@54.190.26.250:26656,b6888552abdf9cb71b175a002160a09bd0690dfe@54.184.71.154:26656,38e4428ac919a6c6b06a5279014a181a60e9ae36@54.200.73.105:26656"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "data/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

# Maximum size of a single transaction.
# NOTE: the max size of a tx transmitted over the network is {max_tx_bytes} + {amino overhead}.
max_tx_bytes = 1048576

##### fast sync configuration options #####
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
version = "v0"

##### consensus configuration options #####
[consensus]

wal_file = "data/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "3m"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "drive_tendermint"
