name: Package Tests

on:
  workflow_call:
    inputs:
      package:
        description: The calling package
        type: string
        default: .

jobs:
  test:
    name: Test Dash Platform component
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Enable NPM cache
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm ci

      - name: Install Packster
        run: npm install -g packster

      # Exit with error here if dependencies are not configured correctly
      - name: Run Packster
        run: packster check ${{ inputs.package }}

      - name: Run ESLinter
        run: npm run lint -w ${{ inputs.package }}

      - name: Get list of packages to test
        id: deps-list
        run: packster list ${{ inputs.package }} > package-list.txt

      - name: Show registered packster list output
        run: cat package-list.txt

      - name: Convert Packster output to JSON
        uses: actions/github-script@v5
        id: deps-json
        with:
          result-encoding: string
          script: |
            fetch("./package-list.txt")
              .then(res => res.json())
              .then(data => console.log(data));

      - name: Run tests on packages
        run: |
          readarray -t deps < <(jq -r '.[] | .[]' < echo ${{ steps.deps-json.outputs.result }})
          for dep in "${deps[@]}"; done npm run test -w "$dep"; done
