version: '3.7'

services:
  dapi_api:
    build:
      context: ../../
      dockerfile: ${PLATFORM_DAPI_API_DOCKER_BUILD_PATH:?err}/Dockerfile
    image: dapi:local

  dapi_tx_filter_stream:
    build:
      context: ../../
      dockerfile: ${PLATFORM_DAPI_API_DOCKER_BUILD_PATH:?err}/Dockerfile
    image: dapi:local
