version: '3'

services:
  core:
    image: $REPO_URL/dashevo/dashcore:develop
    restart: always
    ports:
      - $DASHD_PORT:$DASHD_PORT
      - 127.0.0.1:$DASHD_RPC_PORT:20002
      - 127.0.0.1:$DASHD_ZMQ_PORT:29998
    volumes:
      - ./data/dash.conf:/dash/dash.conf
      - ./data/dash.conf:/root/.dashcore/dash.conf # Make dash-cli inside the container work
      - ./data/$DASHD_DATADIR:/data
    command: dashd -conf=/dash/dash.conf -datadir=/data -port=$DASHD_PORT $DASHD_SEED_NODE_ARGS $DASHD_NETWORK_ARGS $MASTERNODE_ARGS $EXTERNALIP_ARGS

  sentinel:
    image: ablock/sentinel
    restart: always
    environment:
      - DEBUG=false
      - RPCUSER=dashrpc
      - RPCPASSWORD=password
      - RPCHOST=core
      - RPCPORT=20002
      - NETWORK=$DASH_NETWORK

  ipfs:
    image: ipfs/go-ipfs:v0.4.15
    ports:
      - 4001:4001
      - 4001:4002/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    volumes:
      - ipfs:/data/ipfs
    command: daemon --migrate=true --enable-pubsub-experiment --offline

  insight:
    image: $REPO_URL/dashevo/evoinsight:latest
    restart: always
    depends_on:
      - core
    ports:
      - 127.0.0.1:3001:3001
    links:
      - core:dashcore
    volumes:
      - ./data/bitcore-node-dash.json:/insight/bitcore-node-dash.json

  drive_mongodb:
    image: mongo:3.6
    volumes:
      - drive_mongodb:/data/db

  drive_sync:
    image: $REPO_URL/dashevo/dashdrive:latest
    command: npm run sync
    restart: always
    depends_on:
      - core
      - ipfs
      - drive_mongodb
    environment:
      - DASHCORE_JSON_RPC_HOST=core
      - DASHCORE_JSON_RPC_PORT=20002
      - STORAGE_MONGODB_URL=mongodb://drive_mongodb:27017

  drive_api:
    image: $REPO_URL/dashevo/dashdrive:latest
    command: npm run api
    restart: always
    depends_on:
      - core
      - ipfs
      - drive_mongodb
    ports:
      - 127.0.0.1:6000:5001
    environment:
      - DASHCORE_JSON_RPC_HOST=core
      - DASHCORE_JSON_RPC_PORT=20002
      - STORAGE_MONGODB_URL=mongodb://drive_mongodb:27017

  dapi:
    image: $REPO_URL/dashevo/dapi:latest
    restart: always
    depends_on:
      - core
      - ipfs
      - insight
    ports:
      - 3000:3000
    environment:
      - INSIGHT_URI=http://insight:3001/insight-api-dash
      - RPC_SERVER_PORT=3000
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=20002
      - DASHCORE_RPC_USER=dashrpc
      - DASHCORE_RPC_PASS=password
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=29998
      - NETWORK=$DASH_NETWORK

volumes:
  drive_mongodb:
  ipfs:
