version: '3.7'

services:
  drive_mongodb:
    image: ${PLATFORM_DRIVE_MONGODB_DOCKER_IMAGE:?err}
    restart: unless-stopped
    volumes:
      - drive_mongodb_data:/data/db
      - ./docker/mongodb/initiate_mongodb_replica.js:/docker-entrypoint-initdb.d/initiate_mongodb_replica.js
    extra_hosts:
      - "drive_mongodb:127.0.0.1"
    command: mongod --replSet driveDocumentIndices --bind_ip_all

  drive_abci:
    image: ${PLATFORM_DRIVE_ABCI_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - drive_mongodb
      - core
    volumes:
      - drive_abci_data:/usr/src/app/db
      - type: bind
        source: ${PLATFORM_DRIVE_ABCI_LOG_PRETTY_FILE_PATH:?err}
        target: /var/log/drive-pretty.log
      - type: bind
        source: ${PLATFORM_DRIVE_ABCI_LOG_JSON_FILE_PATH:?err}
        target: /var/log/drive-json.log
    environment:
      - CORE_JSON_RPC_USERNAME=${CORE_RPC_USER:?err}
      - CORE_JSON_RPC_PASSWORD=${CORE_RPC_PASSWORD:?err}
      - CORE_JSON_RPC_HOST=core
      - CORE_JSON_RPC_PORT=${CORE_RPC_PORT:?err}
      - CORE_ZMQ_HOST=core
      - CORE_ZMQ_PORT=29998
      - DOCUMENT_MONGODB_URL=mongodb://drive_mongodb:27017?replicaSet=driveDocumentIndices
      - DPNS_CONTRACT_ID=${PLATFORM_DPNS_CONTRACT_ID}
      - DPNS_CONTRACT_BLOCK_HEIGHT=${PLATFORM_DPNS_CONTRACT_BLOCK_HEIGHT}
      - DPNS_TOP_LEVEL_IDENTITY=${PLATFORM_DPNS_OWNER_ID}
      - DASHPAY_CONTRACT_ID=${PLATFORM_DASHPAY_CONTRACT_ID}
      - DASHPAY_CONTRACT_BLOCK_HEIGHT=${PLATFORM_DASHPAY_CONTRACT_BLOCK_HEIGHT}
      - FEATURE_FLAGS_CONTRACT_ID=${PLATFORM_FEATURE_FLAGS_CONTRACT_ID}
      - FEATURE_FALGS_CONTRACT_BLOCK_HEIGHT=${PLATFORM_FEATURE_FLAGS_CONTRACT_BLOCK_HEIGHT}
      - FEATURE_FLAGS_TOP_LEVEL_IDENTITY=${PLATFORM_FEATURE_FLAGS_OWNER_ID}
      - NODE_ENV=${ENVIRONMENT:?err}
      - LOG_STDOUT_LEVEL=${PLATFORM_DRIVE_ABCI_LOG_STDOUT_LEVEL:?err}
      - LOG_PRETTY_FILE_LEVEL=${PLATFORM_DRIVE_ABCI_LOG_PRETTY_FILE_LEVEL:?err}
      - LOG_PRETTY_FILE_PATH=/var/log/drive-pretty.log
      - LOG_JSON_FILE_LEVEL=${PLATFORM_DRIVE_ABCI_LOG_JSON_FILE_LEVEL:?err}
      - LOG_JSON_FILE_PATH=/var/log/drive-json.log
      - INITIAL_CORE_CHAINLOCKED_HEIGHT=${PLATFORM_DRIVE_TENDERDASH_GENESIS_INITIAL_CORE_CHAIN_LOCKED_HEIGHT:-1}
      - NETWORK=${NETWORK}
    command: npm run abci

  drive_tenderdash:
    image: ${PLATFORM_DRIVE_TENDERDASH_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - drive_abci
    ports:
      - ${PLATFORM_DRIVE_TENDERDASH_P2P_PORT:?err}:26656 # P2P
      - 127.0.0.1:${PLATFORM_DRIVE_TENDERDASH_RPC_PORT:?err}:26657 # RPC
    volumes:
      - drive_tenderdash:/tenderdash
      - ${MN_HOME_DIR:?err}/${CONFIG_NAME:?err}/platform/drive/tenderdash:/tenderdash/config:ro

  dapi_api:
    image: ${PLATFORM_DAPI_API_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - drive_tenderdash
      - core
    environment:
      - API_JSON_RPC_PORT=3004
      - API_GRPC_PORT=3005
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=${CORE_RPC_PORT:?err}
      - DASHCORE_RPC_USER=${CORE_RPC_USER:?err}
      - DASHCORE_RPC_PASS=${CORE_RPC_PASSWORD:?err}
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=29998
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=${CORE_P2P_PORT:?err}
      - DASHCORE_P2P_NETWORK=devnet
      - NETWORK=devnet
      - TENDERMINT_RPC_HOST=drive_tenderdash
      - TENDERMINT_RPC_PORT=26657
      - NODE_ENV=${ENVIRONMENT:?err}
    command: npm run api

  dapi_tx_filter_stream:
    image: ${PLATFORM_DAPI_API_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - core
    environment:
      - TX_FILTER_STREAM_GRPC_PORT=3006
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=${CORE_RPC_PORT:?err}
      - DASHCORE_RPC_USER=${CORE_RPC_USER:?err}
      - DASHCORE_RPC_PASS=${CORE_RPC_PASSWORD:?err}
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=29998
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=${CORE_P2P_PORT:?err}
      - DASHCORE_P2P_NETWORK=devnet
      - NETWORK=devnet
      - TENDERMINT_RPC_HOST=drive_tenderdash
      - TENDERMINT_RPC_PORT=26657
    command: npm run tx-filter-stream

  dapi_envoy:
    image: ${PLATFORM_DAPI_ENVOY_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - dapi_api
      - dapi_tx_filter_stream
    volumes:
      - ${MN_HOME_DIR:?err}/${CONFIG_NAME:?err}/platform/dapi/envoy/grpc.yaml:/etc/envoy/envoy.yaml

  dapi_nginx:
    image: ${PLATFORM_DAPI_NGINX_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - dapi_api
      - dapi_tx_filter_stream
      - dapi_envoy
    ports:
      - ${PLATFORM_DAPI_NGINX_HTTP_PORT:?err}:80 # JSON RPC and gRPC Web
      - ${PLATFORM_DAPI_NGINX_GRPC_PORT:?err}:50051 # gRPC Native
    volumes:
      - ${MN_HOME_DIR:?err}/${CONFIG_NAME:?err}/platform/dapi/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${MN_HOME_DIR:?err}/${CONFIG_NAME:?err}/platform/dapi/nginx/grpc.conf:/etc/nginx/conf.d/grpc.conf
      - ${MN_HOME_DIR:?err}/${CONFIG_NAME:?err}/platform/dapi/nginx/errors.grpc_conf:/etc/nginx/conf.d/errors.grpc_conf

volumes:
  drive_abci_data:
  drive_mongodb_data:
  drive_tenderdash:
