version: '3.7'

services:
  core:
    image: ${CORE_DOCKER_IMAGE:?err}:${CORE_VERSION:?err}
    restart: unless-stopped
    ports:
      - ${CORE_P2P_PORT:?err}:${CORE_P2P_PORT:?err} # P2P
    volumes:
      - ./configs/${NETWORK:?err}/core/dashd.conf:/dash/.dashcore/dash.conf
      - ./data/${NETWORK:?err}/core:/dash/data
    command:
      - dashd
      - -conf=/dash/.dashcore/dash.conf
      - -datadir=/dash/data
      - -port=${CORE_P2P_PORT:?err}
      - -masternodeblsprivkey=${CORE_MASTERNODE_OPERATOR_PRIVATE_KEY}
      - -externalip=${EXTERNAL_IP}

  sentinel:
    image: dashpay/sentinel
    restart: unless-stopped
    depends_on:
      - core
    environment:
      - DEBUG=false
      - RPCUSER=dashrpc
      - RPCPASSWORD=password
      - RPCHOST=core
      - RPCPORT=20002
      - NETWORK=${NETWORK?:err}
      - SENTINEL_ARGS=-b
