version: '3'

services:
  core:
    image: $REPO_URL/dashevo/dashcore:develop
    restart: always
    ports:
      - 19999:19999
      - 127.0.0.1:19998:19998
      - 127.0.0.1:29998:29998
    volumes:
      - ./data/dash.conf:/dash/dash.conf
      - ./data/core:/data

  ipfs:
    image: jbenet/go-ipfs:latest
    ports:
      - 4001:4001
      - 4001:4002/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    volumes:
      - ./data/ipfs:/data/ipfs
    command: daemon --migrate=true --enable-pubsub-experiment

  insight:
    image: $REPO_URL/dashevo/evoinsight:latest
    restart: always
    ports:
      - 127.0.0.1:3001:3001
    links:
      - core:dashcore
    volumes:
      - ./data/bitcore-node-dash.json:/insight/bitcore-node-dash.json

  drive:
    image: $REPO_URL/dashevo/dashdrive:latest
    restart: always
    ports:
      - 127.0.0.1:6000:5001

  dapi:
    image: $REPO_URL/dashevo/dapi:latest
    restart: always
    ports:
      - 127.0.0.1:6001:3000
