version: '3.7'

services:
  core:
    image: dashpay/dashd:${CORE_VERSION:-latest}
    restart: always
    ports:
      - 20001:20001 # P2P
    volumes:
      - ./configs/${PRESET:?err}/core/dashd.conf:/dash/.dashcore/dash.conf
      - ./data/${PRESET:?err}/core:/data
    command:
      - dashd
      - -conf=/dash/.dashcore/dash.conf
      - -datadir=/data
      - -masternodeblsprivkey=${CORE_MASTERNODE_BLS_PRIV_KEY:?err}
      - -externalip=${CORE_EXTERNAL_IP:?err}

  sentinel:
    image: ablock/sentinel
    restart: always
    depends_on:
      - core
    environment:
      - DEBUG=false
      - RPCUSER=dashrpc
      - RPCPASSWORD=password
      - RPCHOST=core
      - RPCPORT=20002
      - NETWORK=${SENTINEL_NETWORK}
      - SENTINEL_ARGS=-b

  drive_mongodb:
    image: mongo:${DRIVE_MONGODB_VERSION:-4.2}
    restart: always
    volumes:
      - drive_mongodb:/data/db
    command: mongod --replSet driveDocumentIndices --bind_ip_all

  drive_mongodb_replica_init:
    image: mongo:${DRIVE_MONGODB_VERSION:-4.2}
    depends_on:
      - drive_mongodb
    volumes:
      - ./scripts/initiate_mongodb_replica.sh:/initiate_mongodb_replica.sh
    entrypoint: /initiate_mongodb_replica.sh

  drive_update_state:
    image: dashpay/drive:${DRIVE_VERSION:-latest}
    restart: always
    depends_on:
      - drive_mongodb_replica_init
      - core
    environment:
      - DASHCORE_JSON_RPC_USER=dashrpc
      - DASHCORE_JSON_RPC_PASS=password
      - DASHCORE_JSON_RPC_HOST=core
      - DASHCORE_JSON_RPC_PORT=20002
      - STATEVIEW_MONGODB_URL=mongodb://drive_mongodb:27017
      - UPDATE_STATE_GRPC_PORT=5000
      - TENDERMINT_RPC_HOST=tendermint
      - TENDERMINT_RPC_PORT=26657
      - DPNS_CONTRACT_ID=${DPNS_CONTRACT_ID}
      - DPNS_TOP_LEVEL_IDENTITY=${DPNS_TOP_LEVEL_IDENTITY}
    command: sh -c "sleep 15 && npm run updateState"

  drive_api:
    image: dashpay/drive:${DRIVE_VERSION:-latest}
    restart: always
    depends_on:
      - drive_mongodb_replica_init
      - core
    environment:
      - DASHCORE_JSON_RPC_USER=dashrpc
      - DASHCORE_JSON_RPC_PASS=password
      - DASHCORE_JSON_RPC_HOST=core
      - DASHCORE_JSON_RPC_PORT=20002
      - STATEVIEW_MONGODB_URL=mongodb://drive_mongodb:27017
      - API_RPC_PORT=6000
      - TENDERMINT_RPC_HOST=tendermint
      - TENDERMINT_RPC_PORT=26657
    command: sh -c "sleep 15 && npm run api"

  machine:
    image: dashpay/js-machine:${MACHINE_VERSION:-latest}
    restart: always
    depends_on:
      - drive_api
      - drive_update_state
    environment:
      - DRIVE_UPDATE_STATE_HOST=drive_update_state
      - DRIVE_UPDATE_STATE_PORT=5000
      - DRIVE_API_HOST=drive_api
      - DRIVE_API_PORT=6000
      - RATE_LIMITER_ACTIVE=false
      - RATE_LIMITER_MAX_TRANSITIONS_PER_ID=100
      - RATE_LIMITER_PER_BLOCK_INTERVAL=36
      - RATE_LIMITER_PER_BAN_INTERVAL=17280
      - RATE_LIMITER_INTERVAL_PREFIX='ratelimiter.interval'
      - RATE_LIMITER_BAN_PREFIX='ratelimiter.ban'
    volumes:
      - machine_leveldb:/usr/src/app/db
    command: npm run abci

  tendermint:
    image: tendermint/tendermint:${TENDERMINT_VERSION:-v0.32.8}
    restart: always
    depends_on:
      - machine
    ports:
      - 26656:26656 # P2P
    volumes:
      - ./configs/${PRESET:?err}/tendermint:/tendermint
      - ./data/${PRESET:?err}/tendermint:/data
    entrypoint: sh -c "sleep 30 && /usr/bin/tendermint init && /usr/bin/tendermint node"

  dapi_insight:
    image: dashpay/insight-api:${DAPI_INSIGHT_VERSION:-latest}
    restart: always
    depends_on:
      - core
    volumes:
      - ./configs/${PRESET:?err}/dapi-insight/dashcore-node.json:/insight/dashcore-node.json

  dapi_api:
    image: dashpay/dapi:${DAPI_VERSION:-latest}
    restart: always
    depends_on:
      - tendermint
      - dapi_insight
      - core
      - drive_api
    environment:
      - INSIGHT_URI=http://dapi_insight:3001/insight-api
      - API_JSON_RPC_PORT=3004
      - API_GRPC_PORT=3005
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=20002
      - DASHCORE_RPC_USER=dashrpc
      - DASHCORE_RPC_PASS=password
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=29998
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=20001
      - DASHCORE_P2P_NETWORK=devnet
      - DRIVE_RPC_HOST=drive_api
      - DRIVE_RPC_PORT=6000
      - NETWORK=devnet
      - TENDERMINT_CORE_HOST=tendermint
      - TENDERMINT_CORE_PORT=26657
    command: npm run api

  dapi_tx_filter_stream:
    image: dashpay/dapi:${DAPI_VERSION:-latest}
    restart: always
    depends_on:
      - core
      - drive_api
    environment:
      - INSIGHT_URI=http://dapi_insight:3001/insight-api
      - TX_FILTER_STREAM_GRPC_PORT=3006
      - DASHCORE_RPC_HOST=core
      - DASHCORE_RPC_PORT=20002
      - DASHCORE_RPC_USER=dashrpc
      - DASHCORE_RPC_PASS=password
      - DASHCORE_ZMQ_HOST=core
      - DASHCORE_ZMQ_PORT=29998
      - DASHCORE_P2P_HOST=core
      - DASHCORE_P2P_PORT=20001
      - DASHCORE_P2P_NETWORK=devnet
      - DRIVE_RPC_HOST=drive_api
      - DRIVE_RPC_PORT=6000
      - NETWORK=devnet
    command: npm run tx-filter-stream

  dapi_envoy:
    image: envoyproxy/envoy:${DAPI_ENVOY_VERSION:-latest}
    restart: always
    depends_on:
      - dapi_api
      - dapi_tx_filter_stream
    volumes:
      - ./configs/${PRESET:?err}/envoy/grpc.yaml:/etc/envoy/envoy.yaml

  dapi_nginx:
    image: nginx:${DAPI_NGINX_VERSION:-latest}
    restart: always
    depends_on:
      - dapi_api
      - dapi_tx_filter_stream
      - dapi_envoy
    ports:
      - 3000:80 # JSON RPC and gRPC Web
      - 3010:50051 # gRPC Native
    volumes:
      - ./configs/${PRESET:?err}/dapi-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./configs/${PRESET:?err}/dapi-nginx/grpc.conf:/etc/nginx/conf.d/grpc.conf
      - ./configs/${PRESET:?err}/dapi-nginx/errors.grpc_conf:/etc/nginx/conf.d/errors.grpc_conf

volumes:
  drive_mongodb:
  machine_leveldb:
